name: Native Tests

on:
  workflow_call:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Tools (For local act simulator)
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Build & Test (Standard Mode)
        run: |
          cmake -B build_std -DCMAKE_BUILD_TYPE=Release -DFASTCRON_BUILD_TESTS=ON -DFASTCRON_STRICT_MISRA=OFF
          cmake --build build_std --config Release
          ctest --test-dir build_std --output-on-failure -C Release

      - name: Build & Test (MISRA Mode)
        run: |
          cmake -B build_misra -DCMAKE_BUILD_TYPE=Release -DFASTCRON_BUILD_TESTS=ON -DFASTCRON_STRICT_MISRA=ON
          cmake --build build_misra --config Release
          ctest --test-dir build_misra --output-on-failure -C Release
